import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Bill, Invoice, BusinessSettings } from '@/types/erp';

export const generateBillPDF = async (bill: Bill, settings?: BusinessSettings) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(30, 64, 175);
  doc.text('BILL', doc.internal.pageSize.getWidth() / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text(settings?.name || 'Medha Sanitary & Hardware', doc.internal.pageSize.getWidth() / 2, 28, { align: 'center' });
  
  // Bill Details Box
  doc.setFillColor(249, 250, 251);
  doc.rect(15, 40, 180, 40, 'F');
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Bill ID', 20, 48);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(bill.id, 20, 54);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Date', 110, 48);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(bill.date, 110, 54);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Supplier', 20, 63);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(bill.supplier, 20, 69);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Due Date', 110, 63);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.text(bill.dueDate, 110, 69);
  
  let yPos = 90;
  
  // GST Breakdown if available
  if (bill.subtotal && settings?.gstEnabled) {
    doc.setFillColor(249, 250, 251);
    doc.rect(15, yPos, 180, 40, 'F');
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139);
    doc.text('Subtotal', 20, yPos + 8);
    doc.setTextColor(0, 0, 0);
    doc.text(`₹${bill.subtotal.toFixed(2)}`, 175, yPos + 8, { align: 'right' });
    
    if (bill.cgst && bill.sgst) {
      doc.setTextColor(100, 116, 139);
      doc.text(`CGST (${(bill.gstRate || 0) / 2}%)`, 20, yPos + 16);
      doc.setTextColor(0, 0, 0);
      doc.text(`₹${bill.cgst.toFixed(2)}`, 175, yPos + 16, { align: 'right' });
      
      doc.setTextColor(100, 116, 139);
      doc.text(`SGST (${(bill.gstRate || 0) / 2}%)`, 20, yPos + 24);
      doc.setTextColor(0, 0, 0);
      doc.text(`₹${bill.sgst.toFixed(2)}`, 175, yPos + 24, { align: 'right' });
    } else if (bill.igst) {
      doc.setTextColor(100, 116, 139);
      doc.text(`IGST (${bill.gstRate || 0}%)`, 20, yPos + 16);
      doc.setTextColor(0, 0, 0);
      doc.text(`₹${bill.igst.toFixed(2)}`, 175, yPos + 16, { align: 'right' });
    }
    
    yPos += 45;
  }
  
  // Total Amount Box
  doc.setFillColor(249, 250, 251);
  doc.rect(15, yPos, 180, 25, 'F');
  
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text('Total Amount', 20, yPos + 10);
  
  doc.setFontSize(20);
  doc.setTextColor(30, 64, 175);
  doc.text(`₹${bill.total.toFixed(2)}`, 175, yPos + 17, { align: 'right' });
  
  yPos += 35;
  
  // Notes
  if (bill.notes) {
    doc.setFillColor(254, 243, 199);
    doc.rect(15, yPos, 180, 20, 'F');
    doc.setFontSize(10);
    doc.setTextColor(146, 64, 14);
    doc.text('Notes:', 20, yPos + 8);
    doc.setTextColor(120, 53, 15);
    doc.text(bill.notes, 20, yPos + 15, { maxWidth: 170 });
  }
  
  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by Medha ERP System', doc.internal.pageSize.getWidth() / 2, footerY, { align: 'center' });
  
  doc.save(`Bill_${bill.id}_${bill.supplier}.pdf`);
};

export const downloadInvoicePDF = async (invoice: Invoice, settings?: BusinessSettings) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(24);
  doc.setTextColor(30, 64, 175);
  doc.text('TAX INVOICE', doc.internal.pageSize.getWidth() / 2, 20, { align: 'center' });
  
  // Business Details
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(settings?.name || 'Medha Sanitary & Hardware', 15, 35);
  
  if (settings?.address) {
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(settings.address, 15, 41, { maxWidth: 80 });
  }
  
  if (settings?.gstNumber) {
    doc.text(`GST: ${settings.gstNumber}`, 15, 51);
  }
  
  if (settings?.phone) {
    doc.text(`Phone: ${settings.phone}`, 15, 56);
  }
  
  // Invoice Details Box
  doc.setFillColor(249, 250, 251);
  doc.rect(120, 35, 75, 25, 'F');
  
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Invoice No:', 125, 41);
  doc.setTextColor(0, 0, 0);
  doc.text(invoice.id, 160, 41);
  
  doc.setTextColor(100, 116, 139);
  doc.text('Date:', 125, 47);
  doc.setTextColor(0, 0, 0);
  doc.text(invoice.date, 160, 47);
  
  doc.setTextColor(100, 116, 139);
  doc.text('Due Date:', 125, 53);
  doc.setTextColor(0, 0, 0);
  doc.text(invoice.dueDate, 160, 53);
  
  // Customer Details
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Bill To:', 15, 70);
  doc.setFontSize(11);
  doc.setTextColor(0, 0, 0);
  doc.text(invoice.customer, 15, 76);
  
  // Items Table
  const tableData = invoice.items.map(item => [
    item.name,
    item.qty.toString(),
    `₹${item.rate.toFixed(2)}`,
    `₹${item.amount.toFixed(2)}`
  ]);
  
  autoTable(doc, {
    startY: 85,
    head: [['Item', 'Qty', 'Rate', 'Amount']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [102, 126, 234] },
    styles: { fontSize: 10 },
  });
  
  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  // Tax Breakdown
  const taxBoxX = 120;
  let taxY = finalY;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text('Subtotal:', taxBoxX, taxY);
  doc.setTextColor(0, 0, 0);
  doc.text(`₹${invoice.subtotal.toFixed(2)}`, 190, taxY, { align: 'right' });
  
  if (settings?.gstEnabled && invoice.gstRate) {
    taxY += 7;
    
    if (invoice.cgst && invoice.sgst) {
      doc.setTextColor(100, 116, 139);
      doc.text(`CGST (${invoice.gstRate / 2}%):`, taxBoxX, taxY);
      doc.setTextColor(0, 0, 0);
      doc.text(`₹${invoice.cgst.toFixed(2)}`, 190, taxY, { align: 'right' });
      
      taxY += 7;
      doc.setTextColor(100, 116, 139);
      doc.text(`SGST (${invoice.gstRate / 2}%):`, taxBoxX, taxY);
      doc.setTextColor(0, 0, 0);
      doc.text(`₹${invoice.sgst.toFixed(2)}`, 190, taxY, { align: 'right' });
    } else if (invoice.igst) {
      doc.setTextColor(100, 116, 139);
      doc.text(`IGST (${invoice.gstRate}%):`, taxBoxX, taxY);
      doc.setTextColor(0, 0, 0);
      doc.text(`₹${invoice.igst.toFixed(2)}`, 190, taxY, { align: 'right' });
    }
  }
  
  taxY += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(taxBoxX, taxY, 195, taxY);
  
  taxY += 7;
  doc.setFontSize(14);
  doc.setTextColor(30, 64, 175);
  doc.text('Total:', taxBoxX, taxY);
  doc.text(`₹${invoice.total.toFixed(2)}`, 190, taxY, { align: 'right' });
  
  // Terms
  if (settings?.invoiceTerms) {
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text('Terms & Conditions:', 15, doc.internal.pageSize.getHeight() - 35);
    doc.setFontSize(7);
    doc.text(settings.invoiceTerms, 15, doc.internal.pageSize.getHeight() - 30, { maxWidth: 180 });
  }
  
  // Footer
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('Generated by Medha ERP System', doc.internal.pageSize.getWidth() / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  
  doc.save(`Invoice_${invoice.id}_${invoice.customer}.pdf`);
};

// Alias for compatibility
export const generateInvoicePDF = downloadInvoicePDF;
